config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
 has_many :reviews, dependent: :destroy

 validates :name, presence: true
 validates :address, presence: true
 validates :category, presence: true, inclusion:  ["chinese", "italian", "japanese", "french", "belgian"]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1,2,3,4,5], allow_nil: false }, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_parameters)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_parameters
    params.require(:restaurant).permit(:name, :address, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :find_restaurant, only: [ :new, :create ]

  def new
    @review = Review.new
  end

  def create
    @review = @restaurant.reviews.build(review_params)
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsYelpMvp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/restaurants/index.html.erb
<h1>Here's all the Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Add a restaurant</h1>
      <%= simple_form_for(@restaurant) do |f| %>
        <%= f.error_notification %>

        <%= f.input :name, placeholder: "Choose a restaurant" %>
        <%= f.input :address, placeholder: "Guldbergsgade 11, 2200 København N"  %>
        <%= f.input :phone_number, placeholder: "+61401011461"  %>
        <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"], prompt: "What food would you like?" %>

        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Welcome to <%= @restaurant.name %></h1>

      <div>
        <%= link_to "Add Review", new_restaurant_review_path(@restaurant) %>
      </div>

      <div>
        <%= link_to "Back to list of restaurants", restaurants_path %>
      </div>

    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Add a review</h1>
      <%= simple_form_for [@restaurant, @review] do |f| %>
        <%= f.error_notification %>

        <%= f.input :content, placeholder: "Write your review" %>
        <%= f.input :rating, collection: [1, 2, 3, 4, 5]  %>

        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>